# Generated by Django 5.0.6 on 2024-05-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidadesofertadas',
            name='numeracion',
        ),
        migrations.AddField(
            model_name='localidadesofertadas',
            name='recinto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.recinto'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago_efectuado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='estado',
            field=models.CharField(choices=[('L', 'Libre'), ('R', 'Reservada'), ('P', 'Pre-reservada'), ('D', 'Deteriorada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='localidadesofertadas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta de crédito/débito'), ('Transferencia', 'Transferencia bancaria'), ('Paypal', 'PayPal'), ('Efectivo', 'Pago en efectivo'), ('Ninguno', 'Sin especificar')], max_length=20),
        ),
    ]
