# Generated by Django 5.0.6 on 2024-05-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidadesofertadas',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.reserva'),
        ),
    ]
