# Generated by Django 5.0.6 on 2024-05-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_localidadesofertadas_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidadesofertadas',
            name='reserva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reserva'),
        ),
    ]
